// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ya-breeze/diary.be/pkg/database (interfaces: Storage)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	database "github.com/ya-breeze/diary.be/pkg/database"
	models "github.com/ya-breeze/diary.be/pkg/database/models"
	gorm "gorm.io/gorm"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddIgnoredOrphan mocks base method.
func (m *MockStorage) AddIgnoredOrphan(arg0 uuid.UUID, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIgnoredOrphan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIgnoredOrphan indicates an expected call of AddIgnoredOrphan.
func (mr *MockStorageMockRecorder) AddIgnoredOrphan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIgnoredOrphan", reflect.TypeOf((*MockStorage)(nil).AddIgnoredOrphan), arg0, arg1)
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// CreateChangeRecord mocks base method.
func (m *MockStorage) CreateChangeRecord(arg0 uuid.UUID, arg1 string, arg2 models.OperationType, arg3 *models.Item, arg4 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChangeRecord", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChangeRecord indicates an expected call of CreateChangeRecord.
func (mr *MockStorageMockRecorder) CreateChangeRecord(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChangeRecord", reflect.TypeOf((*MockStorage)(nil).CreateChangeRecord), arg0, arg1, arg2, arg3, arg4)
}

// CreateFamily mocks base method.
func (m *MockStorage) CreateFamily(arg0 string) (*models.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFamily", arg0)
	ret0, _ := ret[0].(*models.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFamily indicates an expected call of CreateFamily.
func (mr *MockStorageMockRecorder) CreateFamily(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFamily", reflect.TypeOf((*MockStorage)(nil).CreateFamily), arg0)
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(arg0, arg1 string, arg2 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), arg0, arg1, arg2)
}

// DeleteItem mocks base method.
func (m *MockStorage) DeleteItem(arg0 uuid.UUID, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockStorageMockRecorder) DeleteItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockStorage)(nil).DeleteItem), arg0, arg1)
}

// GetAllUsers mocks base method.
func (m *MockStorage) GetAllUsers() ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockStorageMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockStorage)(nil).GetAllUsers))
}

// GetChangesSince mocks base method.
func (m *MockStorage) GetChangesSince(arg0 uuid.UUID, arg1 uint, arg2 int) ([]*models.ItemChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangesSince", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.ItemChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangesSince indicates an expected call of GetChangesSince.
func (mr *MockStorageMockRecorder) GetChangesSince(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangesSince", reflect.TypeOf((*MockStorage)(nil).GetChangesSince), arg0, arg1, arg2)
}

// GetDB mocks base method.
func (m *MockStorage) GetDB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockStorageMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockStorage)(nil).GetDB))
}

// GetFamily mocks base method.
func (m *MockStorage) GetFamily(arg0 uuid.UUID) (*models.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFamily", arg0)
	ret0, _ := ret[0].(*models.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFamily indicates an expected call of GetFamily.
func (mr *MockStorageMockRecorder) GetFamily(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFamily", reflect.TypeOf((*MockStorage)(nil).GetFamily), arg0)
}

// GetFamilyByName mocks base method.
func (m *MockStorage) GetFamilyByName(arg0 string) (*models.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFamilyByName", arg0)
	ret0, _ := ret[0].(*models.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFamilyByName indicates an expected call of GetFamilyByName.
func (mr *MockStorageMockRecorder) GetFamilyByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFamilyByName", reflect.TypeOf((*MockStorage)(nil).GetFamilyByName), arg0)
}

// GetIgnoredOrphans mocks base method.
func (m *MockStorage) GetIgnoredOrphans(arg0 uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIgnoredOrphans", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIgnoredOrphans indicates an expected call of GetIgnoredOrphans.
func (mr *MockStorageMockRecorder) GetIgnoredOrphans(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIgnoredOrphans", reflect.TypeOf((*MockStorage)(nil).GetIgnoredOrphans), arg0)
}

// GetItem mocks base method.
func (m *MockStorage) GetItem(arg0 uuid.UUID, arg1 string) (*models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", arg0, arg1)
	ret0, _ := ret[0].(*models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockStorageMockRecorder) GetItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockStorage)(nil).GetItem), arg0, arg1)
}

// GetItems mocks base method.
func (m *MockStorage) GetItems(arg0 uuid.UUID, arg1 database.SearchParams) ([]*models.Item, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", arg0, arg1)
	ret0, _ := ret[0].([]*models.Item)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetItems indicates an expected call of GetItems.
func (mr *MockStorageMockRecorder) GetItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockStorage)(nil).GetItems), arg0, arg1)
}

// GetLatestChangeID mocks base method.
func (m *MockStorage) GetLatestChangeID(arg0 uuid.UUID) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestChangeID", arg0)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestChangeID indicates an expected call of GetLatestChangeID.
func (mr *MockStorageMockRecorder) GetLatestChangeID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestChangeID", reflect.TypeOf((*MockStorage)(nil).GetLatestChangeID), arg0)
}

// GetNextDate mocks base method.
func (m *MockStorage) GetNextDate(arg0 uuid.UUID, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextDate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextDate indicates an expected call of GetNextDate.
func (mr *MockStorageMockRecorder) GetNextDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextDate", reflect.TypeOf((*MockStorage)(nil).GetNextDate), arg0, arg1)
}

// GetPreviousDate mocks base method.
func (m *MockStorage) GetPreviousDate(arg0 uuid.UUID, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousDate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousDate indicates an expected call of GetPreviousDate.
func (mr *MockStorageMockRecorder) GetPreviousDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousDate", reflect.TypeOf((*MockStorage)(nil).GetPreviousDate), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStorage) GetUser(arg0 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStorageMockRecorder) GetUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStorage)(nil).GetUser), arg0)
}

// GetUserByUsername mocks base method.
func (m *MockStorage) GetUserByUsername(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStorageMockRecorder) GetUserByUsername(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStorage)(nil).GetUserByUsername), arg0)
}

// Open mocks base method.
func (m *MockStorage) Open() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockStorageMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockStorage)(nil).Open))
}

// PutItem mocks base method.
func (m *MockStorage) PutItem(arg0 uuid.UUID, arg1 *models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutItem indicates an expected call of PutItem.
func (mr *MockStorageMockRecorder) PutItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockStorage)(nil).PutItem), arg0, arg1)
}

// PutUser mocks base method.
func (m *MockStorage) PutUser(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutUser indicates an expected call of PutUser.
func (mr *MockStorageMockRecorder) PutUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutUser", reflect.TypeOf((*MockStorage)(nil).PutUser), arg0)
}

// RemoveIgnoredOrphan mocks base method.
func (m *MockStorage) RemoveIgnoredOrphan(arg0 uuid.UUID, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIgnoredOrphan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveIgnoredOrphan indicates an expected call of RemoveIgnoredOrphan.
func (mr *MockStorageMockRecorder) RemoveIgnoredOrphan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIgnoredOrphan", reflect.TypeOf((*MockStorage)(nil).RemoveIgnoredOrphan), arg0, arg1)
}
